
CREATE UNIQUE CLUSTERED INDEX PK___EFMigrationsHistory ON __EFMigrationsHistory (MigrationId)
CREATE NONCLUSTERED INDEX IX_BasketItems_BasketId ON BasketItems (BasketId)
CREATE NONCLUSTERED INDEX IX_BasketItems_ProductId ON BasketItems (ProductId)
CREATE NONCLUSTERED INDEX IX_BasketItems_ProductId1 ON BasketItems (ProductId1)
CREATE UNIQUE CLUSTERED INDEX PK_BasketItems ON BasketItems (Id)
CREATE NONCLUSTERED INDEX IX_Baskets_UserId ON Baskets (UserId)
CREATE UNIQUE CLUSTERED INDEX PK_Baskets ON Baskets (Id)
CREATE NONCLUSTERED INDEX IX_BusinessBankAccounts_BusinessId ON BusinessBankAccounts (BusinessId)
CREATE UNIQUE CLUSTERED INDEX PK_BusinessBankAccounts ON BusinessBankAccounts (Id)
CREATE NONCLUSTERED INDEX IX_Businesses_CategoryId ON Businesses (CategoryId)
CREATE NONCLUSTERED INDEX IX_Businesses_Id ON Businesses (Id)
CREATE NONCLUSTERED INDEX IX_Businesses_OwnerId ON Businesses (OwnerId)
CREATE UNIQUE CLUSTERED INDEX PK_Businesses ON Businesses (Id)
"CREATE NONCLUSTERED INDEX IDX_Campaigns_BusinessId_StartDate ON Campaigns (BusinessId, StartDate)"
CREATE NONCLUSTERED INDEX IDX_Campaigns_EndDate ON Campaigns (EndDate)
CREATE NONCLUSTERED INDEX IX_Campaigns_BusinessId ON Campaigns (BusinessId)
"CREATE NONCLUSTERED INDEX IX_Campaigns_DateRange ON Campaigns (StartDate, EndDate)"
CREATE NONCLUSTERED INDEX IX_Campaigns_Id ON Campaigns (Id)
CREATE UNIQUE CLUSTERED INDEX PK_Campaigns ON Campaigns (Id)
CREATE NONCLUSTERED INDEX IDX_Categories_Id ON Categories (Id)
CREATE UNIQUE CLUSTERED INDEX PK_Categories ON Categories (Id)
CREATE NONCLUSTERED INDEX IX_Comments_ProductId ON Comments (ProductId)
CREATE NONCLUSTERED INDEX IX_Comments_UserId ON Comments (UserId)
CREATE UNIQUE CLUSTERED INDEX PK_Comments ON Comments (Id)
CREATE NONCLUSTERED INDEX IX_Likes_ProductId ON Likes (ProductId)
CREATE NONCLUSTERED INDEX IX_Likes_UserId ON Likes (UserId)
CREATE UNIQUE CLUSTERED INDEX PK_Likes ON Likes (Id)
CREATE NONCLUSTERED INDEX IX_Messages_ReceiverId ON Messages (ReceiverId)
CREATE NONCLUSTERED INDEX IX_Messages_SenderId ON Messages (SenderId)
CREATE UNIQUE CLUSTERED INDEX PK_Messages ON Messages (Id)
CREATE NONCLUSTERED INDEX IDX_OrderItems_OrderId ON OrderItems (OrderId)
CREATE NONCLUSTERED INDEX IDX_OrderItems_ProductId ON OrderItems (ProductId)
CREATE NONCLUSTERED INDEX IX_OrderItems_OrderId ON OrderItems (OrderId)
CREATE NONCLUSTERED INDEX IX_OrderItems_ProductId ON OrderItems (ProductId)
CREATE NONCLUSTERED INDEX IX_OrderItems_ProductId1 ON OrderItems (ProductId1)
CREATE UNIQUE CLUSTERED INDEX PK_OrderItems ON OrderItems (Id)
CREATE NONCLUSTERED INDEX IDX_Orders_OrderDate ON Orders (OrderDate)
CREATE NONCLUSTERED INDEX IDX_Orders_TotalAmount ON Orders (TotalAmount)
"CREATE NONCLUSTERED INDEX IDX_Orders_UserId_OrderDate ON Orders (UserId, OrderDate)"
CREATE NONCLUSTERED INDEX IX_Orders_Id ON Orders (Id)
CREATE NONCLUSTERED INDEX IX_Orders_OrderDate ON Orders (OrderDate)
CREATE NONCLUSTERED INDEX IX_Orders_UserId ON Orders (UserId)
CREATE UNIQUE CLUSTERED INDEX PK_Orders ON Orders (Id)
CREATE UNIQUE CLUSTERED INDEX PK_Payments ON Payments (Id)
CREATE NONCLUSTERED INDEX IDX_Products_BusinessId ON Products (BusinessId)
CREATE NONCLUSTERED INDEX IDX_Products_CategoryId ON Products (CategoryId)
CREATE NONCLUSTERED INDEX IX_Products_BusinessId ON Products (BusinessId)
CREATE NONCLUSTERED INDEX IX_Products_CategoryId ON Products (CategoryId)
CREATE NONCLUSTERED INDEX IX_Products_Id ON Products (Id)
CREATE UNIQUE CLUSTERED INDEX PK_Products ON Products (Id)
CREATE NONCLUSTERED INDEX IX_Reviews_Id ON Reviews (Id)
CREATE NONCLUSTERED INDEX IX_Reviews_ProductId ON Reviews (ProductId)
CREATE NONCLUSTERED INDEX IX_Reviews_Rating ON Reviews (Rating)
CREATE NONCLUSTERED INDEX IX_Reviews_UserId ON Reviews (UserId)
CREATE UNIQUE CLUSTERED INDEX PK_Reviews ON Reviews (Id)
CREATE UNIQUE CLUSTERED INDEX PK_Transactions ON Transactions (Id)
CREATE UNIQUE CLUSTERED INDEX PK_UserRoles ON UserRoles (Id)
CREATE UNIQUE CLUSTERED INDEX PK_Users ON Users (Id)
